In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
parsnp_data = pd.read_csv('/home/Users/rdd4/bronko-test/bronko_test/alignment_comparisons/hiv_evolution_results/S1/parsnp_100_consensus/parsnp.vcf', delimiter='\t', skiprows=5)
ska_data = pd.read_csv('/home/Users/rdd4/bronko-test/bronko_test/alignment_comparisons/hiv_evolution_results/S1/ska/alignment.vcf', delimiter='\t', skiprows=2)
# ska_data = pd.read_csv('/home/Users/rdd4/bronko-test/bronko_test/alignment_comparisons/hiv_evolution_results/S1/ska/alignment_k15.vcf', delimiter='\t', skiprows=2)
# ska_data = pd.read_csv('/home/Users/rdd4/bronko-test/bronko_test/alignment_comparisons/hiv_evolution_results/S1/ska/hiv_lo_snps.vcf', delimiter='\t', skiprows=1)

parsnp_data = parsnp_data.drop(columns=['ancestral_sequence.fa.ref'])

## add .fasta to all cols in ska_data, remove . instances or replace as 0
ska_data.columns = (
    list(ska_data.columns[:9]) +
    [f"{col}.fasta" for col in ska_data.columns[9:]]
)

ska_data = ska_data[ska_data['ALT'] != '.']
ska_data = ska_data.replace('.', 0)

/tmp/ipykernel_3497913/3292185192.py:15: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ska_data = ska_data.replace('.', 0)

In [4]:
parsnp_data[(parsnp_data["POS"]==5006) | (parsnp_data["POS"]==5010)]

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,24-10-0.056004.fasta,...,58-54-0.413551.fasta,18-30-0.060340.fasta,2-52-0.362219.fasta,22-48-0.304350.fasta,34-73-0.334718.fasta,36-97-0.371712.fasta,4-25-0.459532.fasta,10-83-0.076895.fasta,20-0-0.306216.fasta,80-3-0.454627.fasta
1061,Ancestral,5006,GTATGCAAGA.GTAAGTGATA,G,A,40,PASS,NaN,GT,0,...,1,0,0,0,0,0,0,0,0,1
1063,Ancestral,5010,GCAAGAGTAA.GTGATAGTTG,G,A,40,PASS,NaN,GT,0,...,1,0,0,0,1,0,0,0,0,1

In [5]:
test = parsnp_data.iloc[:,9:]
print((test==0).sum().sum())
print((test==1).sum().sum())
print((test==2).sum().sum())
print((test==3).sum().sum())
print((test==1).sum().sum() + (test==2).sum().sum() + (test==3).sum().sum())

69447
9398
767
51
10216

In [6]:
k = 21  # window size

def get_num_within_k(parsnp_data, k=21):
    pos = parsnp_data["POS"].to_numpy()
    sample_cols = parsnp_data.columns[9:]

    results = {}
    close_locations = {}  # store tuples of nearby variant positions

    num_variants_per_sample = []

    for col in sample_cols:
        idx = np.where(parsnp_data[col].to_numpy() == 1)[0]
        num_variants_per_sample.append(len(idx))
        
        if len(idx) < 2:
            results[col] = 0
            close_locations[col] = []
            continue
        
        sample_pos = pos[idx]
        diffs = np.diff(sample_pos)
        
        threshold = k//2 + 1
        close_mask = diffs <= threshold
        
        # ---- collect tuples ----
        pairs = [
            (sample_pos[i], sample_pos[i+1])
            for i in np.where(close_mask)[0]
        ]
        close_locations[col] = pairs
        
        # ---- counting logic (your original method) ----
        count = (
            close_mask.sum() * 2
            - np.sum(close_mask[:-1] & close_mask[1:])
        )
        
        results[col] = count

    result_series = pd.Series(results)

    result_series
    result_series.sum()
    return result_series, num_variants_per_sample, close_locations

result_series, num_variants_per_sample, close_locations = get_num_within_k(parsnp_data, 21)
result_series_4, num_variants_per_sample_4, close_locations_4 = get_num_within_k(parsnp_data, 9)

In [7]:
print(max(num_variants_per_sample))
print(min(num_variants_per_sample))
print(np.median(num_variants_per_sample))

351
107
222.0

In [8]:
k = 21  # window size

pos = parsnp_data["POS"].to_numpy()
sample_cols = parsnp_data.columns[9:]

results = {}
cluster_locations = {}

for col in sample_cols:
    idx = np.where(parsnp_data[col].to_numpy() == 1)[0]
    
    if len(idx) < 3:
        results[col] = 0
        cluster_locations[col] = []
        continue
    
    sample_pos = pos[idx]
    
    clusters = []
    counted = set()
    
    left = 0
    for right in range(len(sample_pos)):
        
        # shrink window if too large
        while sample_pos[right] - sample_pos[left] > k:
            left += 1
        
        window_size = right - left + 1
        
        if window_size >= 3:
            cluster = tuple(sample_pos[left:right+1])
            clusters.append(cluster)
            counted.update(cluster)
    
    cluster_locations[col] = clusters
    results[col] = len(counted)

result_series = pd.Series(results)

result_series
result_series.sum()

np.int64(2406)

In [9]:
cluster_locations

{'24-10-0.056004.fasta': [(np.int64(369), np.int64(370), np.int64(380)),
  (np.int64(369), np.int64(370), np.int64(380), np.int64(388)),
  (np.int64(544), np.int64(549), np.int64(551)),
  (np.int64(693), np.int64(699), np.int64(704)),
  (np.int64(699), np.int64(704), np.int64(717)),
  (np.int64(765), np.int64(771), np.int64(774)),
  (np.int64(823), np.int64(830), np.int64(831)),
  (np.int64(823), np.int64(830), np.int64(831), np.int64(836)),
  (np.int64(1062), np.int64(1078), np.int64(1082)),
  (np.int64(1078), np.int64(1082), np.int64(1085)),
  (np.int64(1941), np.int64(1949), np.int64(1956)),
  (np.int64(2267), np.int64(2273), np.int64(2276)),
  (np.int64(2267), np.int64(2273), np.int64(2276), np.int64(2284)),
  (np.int64(2430), np.int64(2431), np.int64(2433)),
  (np.int64(2430), np.int64(2431), np.int64(2433), np.int64(2445)),
  (np.int64(2433), np.int64(2445), np.int64(2453)),
  (np.int64(2445), np.int64(2453), np.int64(2459)),
  (np.int64(2477), np.int64(2483), np.int64(2489)),
  (np.int64(2477), np.int64(2483), np.int64(2489), np.int64(2492)),
  (np.int64(2649), np.int64(2653), np.int64(2668)),
  (np.int64(2653), np.int64(2668), np.int64(2674)),
  (np.int64(3173), np.int64(3177), np.int64(3194)),
  (np.int64(3177), np.int64(3194), np.int64(3196)),
  (np.int64(3775), np.int64(3785), np.int64(3793)),
  (np.int64(4068), np.int64(4076), np.int64(4086)),
  (np.int64(4117), np.int64(4134), np.int64(4136)),
  (np.int64(4134), np.int64(4136), np.int64(4142)),
  (np.int64(4694), np.int64(4710), np.int64(4713)),
  (np.int64(4710), np.int64(4713), np.int64(4716)),
  (np.int64(5050), np.int64(5058), np.int64(5062)),
  (np.int64(5854), np.int64(5859), np.int64(5867)),
  (np.int64(5854), np.int64(5859), np.int64(5867), np.int64(5874)),
  (np.int64(6300), np.int64(6304), np.int64(6309)),
  (np.int64(6374), np.int64(6377), np.int64(6380)),
  (np.int64(6374), np.int64(6377), np.int64(6380), np.int64(6382)),
  (np.int64(6380), np.int64(6382), np.int64(6401)),
  (np.int64(6640), np.int64(6642), np.int64(6654)),
  (np.int64(7204), np.int64(7207), np.int64(7211)),
  (np.int64(7204), np.int64(7207), np.int64(7211), np.int64(7219)),
  (np.int64(7204),
   np.int64(7207),
   np.int64(7211),
   np.int64(7219),
   np.int64(7220)),
  (np.int64(7219), np.int64(7220), np.int64(7233)),
  (np.int64(7364), np.int64(7366), np.int64(7371)),
  (np.int64(7413), np.int64(7416), np.int64(7430)),
  (np.int64(8097), np.int64(8101), np.int64(8108)),
  (np.int64(8317), np.int64(8327), np.int64(8330)),
  (np.int64(8317), np.int64(8327), np.int64(8330), np.int64(8338)),
  (np.int64(8327), np.int64(8330), np.int64(8338), np.int64(8348)),
  (np.int64(8397), np.int64(8400), np.int64(8402)),
  (np.int64(8605), np.int64(8618), np.int64(8621)),
  (np.int64(8907), np.int64(8915), np.int64(8925))],
 '14-53-0.427146.fasta': [(np.int64(15), np.int64(22), np.int64(32)),
  (np.int64(492), np.int64(496), np.int64(498)),
  (np.int64(544), np.int64(551), np.int64(554)),
  (np.int64(642), np.int64(651), np.int64(654)),
  (np.int64(642), np.int64(651), np.int64(654), np.int64(658)),
  (np.int64(651), np.int64(654), np.int64(658), np.int64(668)),
  (np.int64(698), np.int64(699), np.int64(714)),
  (np.int64(925), np.int64(937), np.int64(938)),
  (np.int64(937), np.int64(938), np.int64(954)),
  (np.int64(1372), np.int64(1384), np.int64(1385)),
  (np.int64(1372), np.int64(1384), np.int64(1385), np.int64(1391)),
  (np.int64(1384), np.int64(1385), np.int64(1391), np.int64(1402)),
  (np.int64(2445), np.int64(2453), np.int64(2459)),
  (np.int64(2453), np.int64(2459), np.int64(2467)),
  (np.int64(2459), np.int64(2467), np.int64(2475)),
  (np.int64(2467), np.int64(2475), np.int64(2487)),
  (np.int64(2475), np.int64(2487), np.int64(2492)),
  (np.int64(2487), np.int64(2492), np.int64(2502)),
  (np.int64(2649), np.int64(2653), np.int64(2668)),
  (np.int64(3024), np.int64(3029), np.int64(3044)),
  (np.int64(3029), np.int64(3044), np.int64(3046)),
  (np.int64(3044), np.int64(3046), np.int64(3058)),
  (np.int64(3044), np.int64(3046), np.int64(3058), np.int64(3059)),
  (np.int64(3115), np.int64(3129), np.int64(3136)),
  (np.int64(3182), np.int64(3184), np.int64(3196)),
  (np.int64(3923), np.int64(3926), np.int64(3938)),
  (np.int64(4114), np.int64(4117), np.int64(4121)),
  (np.int64(4117), np.int64(4121), np.int64(4136)),
  (np.int64(4577), np.int64(4580), np.int64(4581)),
  (np.int64(5120), np.int64(5124), np.int64(5125)),
  (np.int64(5293), np.int64(5302), np.int64(5303)),
  (np.int64(5592), np.int64(5596), np.int64(5609)),
  (np.int64(5596), np.int64(5609), np.int64(5614)),
  (np.int64(5886), np.int64(5892), np.int64(5901)),
  (np.int64(5886), np.int64(5892), np.int64(5901), np.int64(5902)),
  (np.int64(6024), np.int64(6038), np.int64(6039)),
  (np.int64(6038), np.int64(6039), np.int64(6056)),
  (np.int64(6122), np.int64(6131), np.int64(6143)),
  (np.int64(6249), np.int64(6251), np.int64(6254)),
  (np.int64(6368), np.int64(6382), np.int64(6385)),
  (np.int64(6768), np.int64(6769), np.int64(6770)),
  (np.int64(6768), np.int64(6769), np.int64(6770), np.int64(6778)),
  (np.int64(6831), np.int64(6835), np.int64(6852)),
  (np.int64(6969), np.int64(6973), np.int64(6987)),
  (np.int64(7370), np.int64(7378), np.int64(7386)),
  (np.int64(7370), np.int64(7378), np.int64(7386), np.int64(7390)),
  (np.int64(7413), np.int64(7416), np.int64(7423)),
  (np.int64(7413), np.int64(7416), np.int64(7423), np.int64(7430)),
  (np.int64(7416), np.int64(7423), np.int64(7430), np.int64(7436)),
  (np.int64(7423), np.int64(7430), np.int64(7436), np.int64(7442)),
  (np.int64(7436), np.int64(7442), np.int64(7453)),
  (np.int64(7442), np.int64(7453), np.int64(7461)),
  (np.int64(7453), np.int64(7461), np.int64(7464)),
  (np.int64(7453), np.int64(7461), np.int64(7464), np.int64(7466)),
  (np.int64(7719), np.int64(7722), np.int64(7729)),
  (np.int64(7829), np.int64(7839), np.int64(7849)),
  (np.int64(7965), np.int64(7967), np.int64(7976)),
  (np.int64(8085), np.int64(8096), np.int64(8101)),
  (np.int64(8259), np.int64(8274), np.int64(8279)),
  (np.int64(8274), np.int64(8279), np.int64(8282)),
  (np.int64(8487), np.int64(8492), np.int64(8496)),
  (np.int64(8487), np.int64(8492), np.int64(8496), np.int64(8499)),
  (np.int64(8853), np.int64(8860), np.int64(8861)),
  (np.int64(8914), np.int64(8917), np.int64(8929)),
  (np.int64(9036), np.int64(9050), np.int64(9051))],
 '26-82-0.187728.fasta': [(np.int64(369), np.int64(370), np.int64(380)),
  (np.int64(540), np.int64(544), np.int64(549)),
  (np.int64(684), np.int64(693), np.int64(704)),
  (np.int64(830), np.int64(831), np.int64(844)),
  (np.int64(1500), np.int64(1505), np.int64(1514)),
  (np.int64(1855), np.int64(1861), np.int64(1863)),
  (np.int64(1887), np.int64(1889), np.int64(1907)),
  (np.int64(1941), np.int64(1949), np.int64(1956)),
  (np.int64(1987), np.int64(1990), np.int64(2003)),
  (np.int64(2267), np.int64(2273), np.int64(2276)),
  (np.int64(2267), np.int64(2273), np.int64(2276), np.int64(2284)),
  (np.int64(2430), np.int64(2431), np.int64(2433)),
  (np.int64(2430), np.int64(2431), np.int64(2433), np.int64(2445)),
  (np.int64(2477), np.int64(2483), np.int64(2489)),
  (np.int64(2477), np.int64(2483), np.int64(2489), np.int64(2492)),
  (np.int64(2649), np.int64(2653), np.int64(2668)),
  (np.int64(2653), np.int64(2668), np.int64(2671)),
  (np.int64(2653), np.int64(2668), np.int64(2671), np.int64(2674)),
  (np.int64(3086), np.int64(3105), np.int64(3107)),
  (np.int64(3153), np.int64(3171), np.int64(3173)),
  (np.int64(3303), np.int64(3312), np.int64(3323)),
  (np.int64(3404), np.int64(3415), np.int64(3419)),
  (np.int64(3415), np.int64(3419), np.int64(3429)),
  (np.int64(3419), np.int64(3429), np.int64(3437)),
  (np.int64(3429), np.int64(3437), np.int64(3443)),
  (np.int64(3673), np.int64(3675), np.int64(3680)),
  (np.int64(4068), np.int64(4076), np.int64(4086)),
  (np.int64(4694), np.int64(4710), np.int64(4713)),
  (np.int64(4710), np.int64(4713), np.int64(4716)),
  (np.int64(5048), np.int64(5050), np.int64(5058)),
  (np.int64(5048), np.int64(5050), np.int64(5058), np.int64(5062)),
  (np.int64(5519), np.int64(5529), np.int64(5539)),
  (np.int64(5854), np.int64(5859), np.int64(5867)),
  (np.int64(6300), np.int64(6302), np.int64(6304)),
  (np.int64(6300), np.int64(6302), np.int64(6304), np.int64(6309)),
  (np.int64(6374), np.int64(6377), np.int64(6380)),
  (np.int64(6380), np.int64(6400), np.int64(6401)),
  (np.int64(6400), np.int64(6401), np.int64(6415)),
  (np.int64(6506), np.int64(6507), np.int64(6521)),
  (np.int64(6636), np.int64(6640), np.int64(6642)),
  (np.int64(6636), np.int64(6640), np.int64(6642), np.int64(6654)),
  (np.int64(6636),
   np.int64(6640),
   np.int64(6642),
   np.int64(6654),
   np.int64(6657)),
  (np.int64(6814), np.int64(6828), np.int64(6835)),
  (np.int64(6828), np.int64(6835), np.int64(6843)),
  (np.int64(7204), np.int64(7207), np.int64(7211)),
  (np.int64(7204), np.int64(7207), np.int64(7211), np.int64(7219)),
  (np.int64(7204),
   np.int64(7207),
   np.int64(7211),
   np.int64(7219),
   np.int64(7220)),
  (np.int64(7219), np.int64(7220), np.int64(7233)),
  (np.int64(7411), np.int64(7413), np.int64(7430)),
  (np.int64(7413), np.int64(7430), np.int64(7434)),
  (np.int64(7430), np.int64(7434), np.int64(7442)),
  (np.int64(7595), np.int64(7603), np.int64(7610)),
  (np.int64(7603), np.int64(7610), np.int64(7621)),
  (np.int64(8317), np.int64(8327), np.int64(8330)),
  (np.int64(8317), np.int64(8327), np.int64(8330), np.int64(8338)),
  (np.int64(8327), np.int64(8330), np.int64(8338), np.int64(8348)),
  (np.int64(8338), np.int64(8348), np.int64(8357)),
  (np.int64(8397), np.int64(8400), np.int64(8402)),
  (np.int64(8400), np.int64(8402), np.int64(8421)),
  (np.int64(8605), np.int64(8618), np.int64(8621)),
  (np.int64(8768), np.int64(8774), np.int64(8780)),
  (np.int64(8768), np.int64(8774), np.int64(8780), np.int64(8783)),
  (np.int64(8774), np.int64(8780), np.int64(8783), np.int64(8795)),
  (np.int64(8907), np.int64(8915), np.int64(8925))],
 '74-98-0.056818.fasta': [(np.int64(4999), np.int64(5006), np.int64(5010))],
 '54-16-0.210629.fasta': [(np.int64(146), np.int64(148), np.int64(152)),
  (np.int64(2244), np.int64(2246), np.int64(2256)),
  (np.int64(2314), np.int64(2325), np.int64(2331)),
  (np.int64(2832), np.int64(2834), np.int64(2838)),
  (np.int64(2832), np.int64(2834), np.int64(2838), np.int64(2851)),
  (np.int64(3929), np.int64(3937), np.int64(3945)),
  (np.int64(4427), np.int64(4430), np.int64(4439)),
  (np.int64(5006), np.int64(5008), np.int64(5010)),
  (np.int64(5504), np.int64(5519), np.int64(5522)),
  (np.int64(5519), np.int64(5522), np.int64(5534)),
  (np.int64(6769), np.int64(6773), np.int64(6778)),
  (np.int64(8139), np.int64(8156), np.int64(8160))],
 '52-37-0.259740.fasta': [(np.int64(141), np.int64(146), np.int64(148)),
  (np.int64(141), np.int64(146), np.int64(148), np.int64(152)),
  (np.int64(2314), np.int64(2325), np.int64(2331)),
  (np.int64(2832), np.int64(2834), np.int64(2838)),
  (np.int64(2832), np.int64(2834), np.int64(2838), np.int64(2851)),
  (np.int64(3929), np.int64(3937), np.int64(3945)),
  (np.int64(4742), np.int64(4744), np.int64(4745)),
  (np.int64(5006), np.int64(5008), np.int64(5010)),
  (np.int64(5504), np.int64(5519), np.int64(5522)),
  (np.int64(5519), np.int64(5522), np.int64(5529)),
  (np.int64(5519), np.int64(5522), np.int64(5529), np.int64(5534)),
  (np.int64(6769), np.int64(6773), np.int64(6778))],
 '62-88-0.463081.fasta': [(np.int64(146), np.int64(148), np.int64(152)),
  (np.int64(699), np.int64(702), np.int64(706)),
  (np.int64(2244), np.int64(2246), np.int64(2256)),
  (np.int64(2314), np.int64(2325), np.int64(2331)),
  (np.int64(2723), np.int64(2725), np.int64(2734)),
  (np.int64(2832), np.int64(2834), np.int64(2838)),
  (np.int64(2832), np.int64(2834), np.int64(2838), np.int64(2851)),
  (np.int64(3929), np.int64(3937), np.int64(3945)),
  (np.int64(5006), np.int64(5008), np.int64(5010)),
  (np.int64(5504), np.int64(5519), np.int64(5522)),
  (np.int64(5519), np.int64(5522), np.int64(5534)),
  (np.int64(6769), np.int64(6773), np.int64(6778))],
 '28-5-0.191505.fasta': [(np.int64(823), np.int64(830), np.int64(831)),
  (np.int64(954), np.int64(974), np.int64(975)),
  (np.int64(2267), np.int64(2273), np.int64(2276)),
  (np.int64(2267), np.int64(2273), np.int64(2276), np.int64(2284)),
  (np.int64(2430), np.int64(2431), np.int64(2433)),
  (np.int64(2430), np.int64(2431), np.int64(2433), np.int64(2445)),
  (np.int64(2477), np.int64(2483), np.int64(2489)),
  (np.int64(2477), np.int64(2483), np.int64(2489), np.int64(2492)),
  (np.int64(2649), np.int64(2653), np.int64(2668)),
  (np.int64(3839), np.int64(3855), np.int64(3857)),
  (np.int64(3855), np.int64(3857), np.int64(3871)),
  (np.int64(3926), np.int64(3937), np.int64(3943)),
  (np.int64(4068), np.int64(4076), np.int64(4086)),
  (np.int64(4114), np.int64(4117), np.int64(4134)),
  (np.int64(4117), np.int64(4134), np.int64(4136)),
  (np.int64(4134), np.int64(4136), np.int64(4153)),
  (np.int64(4713), np.int64(4716), np.int64(4732)),
  (np.int64(5439), np.int64(5445), np.int64(5457)),
  (np.int64(6300), np.int64(6304), np.int64(6309)),
  (np.int64(6374), np.int64(6377), np.int64(6380)),
  (np.int64(6640), np.int64(6642), np.int64(6654)),
  (np.int64(7192), np.int64(7199), np.int64(7204)),
  (np.int64(7192), np.int64(7199), np.int64(7204), np.int64(7207)),
  (np.int64(7192),
   np.int64(7199),
   np.int64(7204),
   np.int64(7207),
   np.int64(7211)),
  (np.int64(7199),
   np.int64(7204),
   np.int64(7207),
   np.int64(7211),
   np.int64(7219)),
  (np.int64(8043), np.int64(8050), np.int64(8056)),
  (np.int64(8317), np.int64(8327), np.int64(8330)),
  (np.int64(8327), np.int64(8330), np.int64(8348)),
  (np.int64(8397), np.int64(8400), np.int64(8402)),
  (np.int64(8579), np.int64(8583), np.int64(8590)),
  (np.int64(8605), np.int64(8618), np.int64(8621)),
  (np.int64(8907), np.int64(8915), np.int64(8925))],
 '16-90-0.499308.fasta': [(np.int64(93), np.int64(98), np.int64(105)),
  (np.int64(98), np.int64(105), np.int64(115)),
  (np.int64(105), np.int64(115), np.int64(122)),
  (np.int64(204), np.int64(223), np.int64(224)),
  (np.int64(693), np.int64(699), np.int64(704)),
  (np.int64(765), np.int64(766), np.int64(771)),
  (np.int64(1140), np.int64(1149), np.int64(1158)),
  (np.int64(1256), np.int64(1261), np.int64(1263)),
  (np.int64(1500), np.int64(1503), np.int64(1514)),
  (np.int64(1500), np.int64(1503), np.int64(1514), np.int64(1519)),
  (np.int64(1637), np.int64(1640), np.int64(1645)),
  (np.int64(1872), np.int64(1887), np.int64(1889)),
  (np.int64(2413), np.int64(2428), np.int64(2433)),
  (np.int64(2428), np.int64(2433), np.int64(2445)),
  (np.int64(2628), np.int64(2646), np.int64(2649)),
  (np.int64(2646), np.int64(2649), np.int64(2653)),
  (np.int64(2649), np.int64(2653), np.int64(2668)),
  (np.int64(3429), np.int64(3445), np.int64(3446)),
  (np.int64(3703), np.int64(3712), np.int64(3717)),
  (np.int64(3815), np.int64(3829), np.int64(3832)),
  (np.int64(3855), np.int64(3865), np.int64(3871)),
  (np.int64(4581), np.int64(4589), np.int64(4591)),
  (np.int64(4694), np.int64(4710), np.int64(4713)),
  (np.int64(4775), np.int64(4779), np.int64(4782)),
  (np.int64(4775), np.int64(4779), np.int64(4782), np.int64(4794)),
  (np.int64(5609), np.int64(5622), np.int64(5623)),
  (np.int64(5622), np.int64(5623), np.int64(5641)),
  (np.int64(6239), np.int64(6252), np.int64(6254)),
  (np.int64(6252), np.int64(6254), np.int64(6262)),
  (np.int64(7208), np.int64(7211), np.int64(7219)),
  (np.int64(7208), np.int64(7211), np.int64(7219), np.int64(7224)),
  (np.int64(7219), np.int64(7224), np.int64(7235)),
  (np.int64(7413), np.int64(7430), np.int64(7431)),
  (np.int64(7430), np.int64(7431), np.int64(7442)),
  (np.int64(7466), np.int64(7467), np.int64(7478)),
  (np.int64(8089), np.int64(8101), np.int64(8104)),
  (np.int64(8089), np.int64(8101), np.int64(8104), np.int64(8108)),
  (np.int64(8317), np.int64(8327), np.int64(8330)),
  (np.int64(8760), np.int64(8768), np.int64(8774))],
 '66-33-0.355178.fasta': [(np.int64(1172), np.int64(1180), np.int64(1184)),
  (np.int64(1180), np.int64(1184), np.int64(1198)),
  (np.int64(4999), np.int64(5006), np.int64(5010)),
  (np.int64(5973), np.int64(5980), np.int64(5989)),
  (np.int64(7416), np.int64(7426), np.int64(7434)),
  (np.int64(7426), np.int64(7434), np.int64(7440)),
  (np.int64(7434), np.int64(7440), np.int64(7451)),
  (np.int64(8616), np.int64(8619), np.int64(8625))],
 '46-4-0.031722.fasta': [(np.int64(283), np.int64(288), np.int64(295)),
  (np.int64(1481), np.int64(1497), np.int64(1502)),
  (np.int64(1497), np.int64(1502), np.int64(1513)),
  (np.int64(1605), np.int64(1613), np.int64(1625)),
  (np.int64(1684), np.int64(1685), np.int64(1702)),
  (np.int64(2382), np.int64(2391), np.int64(2399)),
  (np.int64(2641), np.int64(2653), np.int64(2656)),
  (np.int64(2653), np.int64(2656), np.int64(2673)),
  (np.int64(2732), np.int64(2734), np.int64(2743)),
  (np.int64(2732), np.int64(2734), np.int64(2743), np.int64(2744)),
  (np.int64(3171), np.int64(3174), np.int64(3183)),
  (np.int64(3902), np.int64(3905), np.int64(3910)),
  (np.int64(3929), np.int64(3938), np.int64(3945)),
  (np.int64(4236), np.int64(4255), np.int64(4256)),
  (np.int64(4713), np.int64(4715), np.int64(4719)),
  (np.int64(4713), np.int64(4715), np.int64(4719), np.int64(4732)),
  (np.int64(6252), np.int64(6257), np.int64(6262)),
  (np.int64(6252), np.int64(6257), np.int64(6262), np.int64(6264)),
  (np.int64(6899), np.int64(6914), np.int64(6916)),
  (np.int64(7021), np.int64(7029), np.int64(7038)),
  (np.int64(7188), np.int64(7197), np.int64(7200)),
  (np.int64(7235), np.int64(7251), np.int64(7254)),
  (np.int64(7867), np.int64(7881), np.int64(7887)),
  (np.int64(7881), np.int64(7887), np.int64(7902)),
  (np.int64(7887), np.int64(7902), np.int64(7906)),
  (np.int64(8944), np.int64(8945), np.int64(8960)),
  (np.int64(9086), np.int64(9094), np.int64(9100))],
 '6-11-0.092686.fasta': [(np.int64(541), np.int64(544), np.int64(554)),
  (np.int64(544), np.int64(554), np.int64(565)),
  (np.int64(1982), np.int64(1986), np.int64(1987)),
  (np.int64(2381), np.int64(2389), np.int64(2391)),
  (np.int64(2642), np.int64(2649), np.int64(2653)),
  (np.int64(2649), np.int64(2653), np.int64(2668)),
  (np.int64(3991), np.int64(3996), np.int64(4010)),
  (np.int64(6871), np.int64(6881), np.int64(6890)),
  (np.int64(6881), np.int64(6890), np.int64(6902)),
  (np.int64(7413), np.int64(7429), np.int64(7430)),
  (np.int64(7429), np.int64(7430), np.int64(7442)),
  (np.int64(7461), np.int64(7464), np.int64(7466)),
  (np.int64(7461), np.int64(7464), np.int64(7466), np.int64(7475)),
  (np.int64(8605), np.int64(8613), np.int64(8618))],
 '50-70-0.309395.fasta': [(np.int64(283), np.int64(288), np.int64(295)),
  (np.int64(1481), np.int64(1497), np.int64(1502)),
  (np.int64(1497), np.int64(1502), np.int64(1513)),
  (np.int64(2382), np.int64(2391), np.int64(2399)),
  (np.int64(2433), np.int64(2441), np.int64(2448)),
  (np.int64(2641), np.int64(2653), np.int64(2656)),
  (np.int64(2653), np.int64(2656), np.int64(2673)),
  (np.int64(2732), np.int64(2734), np.int64(2744)),
  (np.int64(3902), np.int64(3905), np.int64(3910)),
  (np.int64(3929), np.int64(3938), np.int64(3945)),
  (np.int64(4713), np.int64(4715), np.int64(4719)),
  (np.int64(4713), np.int64(4715), np.int64(4719), np.int64(4732)),
  (np.int64(5010), np.int64(5017), np.int64(5020)),
  (np.int64(6252), np.int64(6257), np.int64(6262)),
  (np.int64(6252), np.int64(6257), np.int64(6262), np.int64(6264)),
  (np.int64(7021), np.int64(7029), np.int64(7038)),
  (np.int64(7188), np.int64(7197), np.int64(7200)),
  (np.int64(7235), np.int64(7251), np.int64(7254)),
  (np.int64(7887), np.int64(7902), np.int64(7906))],
 '40-57-0.343879.fasta': [(np.int64(283), np.int64(288), np.int64(295)),
  (np.int64(283), np.int64(288), np.int64(295), np.int64(296)),
  (np.int64(393), np.int64(406), np.int64(413)),
  (np.int64(1496), np.int64(1497), np.int64(1502)),

In [10]:
ska_data

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,0-23-0.098532.fasta,...,64-65-0.413309.fasta,66-33-0.355178.fasta,68-66-0.019926.fasta,70-28-0.297632.fasta,72-67-0.016729.fasta,74-98-0.056818.fasta,76-55-0.131487.fasta,78-1-0.289326.fasta,80-3-0.454627.fasta,8-99-0.089017.fasta
20,Ancestral,21,0,C,T,0,0,0,GT,0,...,0,0,0,1,0,0,0,0,0,0
21,Ancestral,22,0,A,G,0,0,0,GT,1,...,0,0,0,0,0,0,0,0,0,0
47,Ancestral,48,0,A,"T,G",0,0,0,GT,0,...,0,2,2,0,0,0,0,0,0,0
48,Ancestral,54,0,T,C,0,0,0,GT,0,...,0,0,0,0,0,0,0,0,0,0
49,Ancestral,61,0,A,G,0,0,0,GT,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7156,Ancestral,9165,0,A,G,0,0,0,GT,0,...,0,0,0,0,0,0,0,1,0,0
7160,Ancestral,9169,0,A,G,0,0,0,GT,0,...,0,0,0,0,0,0,0,0,0,0
7163,Ancestral,9172,0,A,G,0,0,0,GT,0,...,0,0,0,0,0,0,0,0,0,0
7166,Ancestral,9175,0,A,G,0,0,0,GT,1,...,0,0,0,0,0,0,0,0,0,0
7168,Ancestral,9177,0,A,G,0,0,0,GT,0,...,0,0,0,0,0,0,1,0,0,0

In [11]:
parsnp_data

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,24-10-0.056004.fasta,...,58-54-0.413551.fasta,18-30-0.060340.fasta,2-52-0.362219.fasta,22-48-0.304350.fasta,34-73-0.334718.fasta,36-97-0.371712.fasta,4-25-0.459532.fasta,10-83-0.076895.fasta,20-0-0.306216.fasta,80-3-0.454627.fasta
0,Ancestral,10,AAAGCGTCTT.TTAAATGGCA,T,C,40,PASS,NaN,GT,0,...,1,0,0,0,0,0,0,0,0,0
1,Ancestral,14,GCGTCTTTAA.ATGGCACCAC,A,G,40,PASS,NaN,GT,0,...,0,0,0,0,1,1,0,0,0,0
2,Ancestral,15,CGTCTTTAAA.TGGCACCACG,T,"C,A,G",40,PASS,NaN,GT,0,...,0,0,0,0,0,0,0,0,0,0
3,Ancestral,21,TAAATGGCAC.CACGGTGAAT,C,T,40,PASS,NaN,GT,0,...,0,0,0,0,1,1,0,0,0,0
4,Ancestral,22,AAATGGCACC.ACGGTGAATA,A,G,40,PASS,NaN,GT,0,...,0,0,1,0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1938,Ancestral,9165,GTCTGAAGTT.AGATAAGAAT,A,G,40,PASS,NaN,GT,0,...,0,0,0,0,0,0,0,0,0,0
1939,Ancestral,9169,GAAGTTAGAT.AAGAATAGAG,A,G,40,PASS,NaN,GT,1,...,0,1,0,1,0,0,0,0,1,0
1940,Ancestral,9172,GTTAGATAAG.AATAGAGCCA,A,G,40,PASS,NaN,GT,0,...,0,0,0,0,1,1,0,0,0,0
1941,Ancestral,9175,AGATAAGAAT.AGAGCCACGA,A,G,40,PASS,NaN,GT,0,...,0,0,1,0,0,0,1,0,0,0
1942,Ancestral,9177,ATAAGAATAG.AGCCACGAAG,A,G,40,PASS,NaN,GT,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
len([col for col in parsnp_data.columns if col.endswith(".fasta")])

41

In [13]:
len([col for col in ska_data.columns if col.endswith(".fasta")])

41

In [14]:
def split_multiple_alt_alleles(df):

    df = df.copy()
    fasta_cols = df.columns[9:]  # sample columns

    multi_mask = df["ALT"].str.contains(",", na=False)

    # Separate multi-ALT rows
    df_multi = df[multi_mask].copy()
    df_single = df[~multi_mask].copy()

    new_rows = []

    for _, row in df_multi.iterrows():

        alts = row["ALT"].split(",")

        for i, alt in enumerate(alts, start=1):  # ALT index = 1-based

            new_row = row.copy()
            new_row["ALT"] = alt

            # Convert sample columns:
            # keep only values equal to this alt index
            for col in fasta_cols:
                new_row[col] = 1 if row[col] == i else 0

            new_rows.append(new_row)

    df_multi_split = pd.DataFrame(new_rows)

    # Combine back
    result = pd.concat([df_single, df_multi_split], ignore_index=True)

    return result

In [15]:
parsnp_data['POS'] = parsnp_data['POS'].astype(int)
ska_data['POS'] = ska_data['POS'].astype(int)

parsnp_data = split_multiple_alt_alleles(parsnp_data)
ska_data = split_multiple_alt_alleles(ska_data)

In [16]:
test = parsnp_data.iloc[:,9:]
print((test==0).sum().sum())
print((test==1).sum().sum())
print((test==2).sum().sum())

80271
10216
0

In [17]:
import os
import pandas as pd


def get_bronko_df(location):
    vcf_files = [f for f in os.listdir(location) if f.endswith(".vcf")]

    variant_dict = {}

    for vcf_file in vcf_files:
        sample_name = vcf_file.replace(".vcf", ".fasta")
        with open(os.path.join(location, vcf_file)) as f:
            for line in f:
                if line.startswith("#"):
                    continue
                fields = line.strip().split("\t")
                chrom, pos, _, ref, alt = fields[:5]
                key = (chrom, pos, ref, alt)
                if key not in variant_dict:
                    variant_dict[key] = {}
                variant_dict[key][sample_name] = 1
                
    print(variant_dict)

    # convert to DataFrame

    bronko = pd.DataFrame.from_dict(variant_dict, orient="index")
    bronko = bronko.fillna(0).astype(int)
    bronko.reset_index(inplace=True)
    bronko.rename(columns={"index": ["CHROM", "POS", "REF", "ALT"]}, inplace=True)

    new_names = ['#CHROM','POS','REF','ALT']
    bronko.columns = new_names + bronko.columns[4:].tolist()
    bronko['POS'] = bronko['POS'].astype(int)
    return bronko

bronko = get_bronko_df("/home/Users/rdd4/bronko-test/bronko_test/alignment_comparisons/hiv_evolution_results/S1/bronko_single_ref")  # change this to your VCF folder path
bronko

# df = bronko.drop(columns='index')

# # save table

# # df.to_csv("variant_presence_matrix.csv", index=False)
# print("Saved variant presence matrix to variant_presence_matrix.csv")

{('Ancestral', '61', 'A', 'G'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '117', 'G', 'T'): {'52-37-0.259740.fasta': 1, '32-77-0.273127.fasta': 1, '56-61-0.198293.fasta': 1, '36-97-0.371712.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1, '34-73-0.334718.fasta': 1}, ('Ancestral', '141', 'G', 'A'): {'52-37-0.259740.fasta': 1}, ('Ancestral', '152', 'A', 'G'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '74-98-0.056818.fasta': 1, '70-28-0.297632.fasta': 1, '54-16-0.210629.fasta': 1, '72-67-0.016729.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '78-1-0.289326.fasta': 1, '58-54-0.413551.fasta': 1, '66-33-0.355178.fasta': 1, '68-66-0.019926.fasta': 1, '60-78-0.305355.fasta': 1, '76-55-0.131487.fasta': 1, '80-3-0.454627.fasta': 1}, ('Ancestral', '173', 'G', 'A'): {'52-37-0.259740.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '187', 'A', 'G'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '260', 'T', 'C'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '267', 'C', 'T'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '68-66-0.019926.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '345', 'A', 'G'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '66-33-0.355178.fasta': 1, '68-66-0.019926.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '515', 'G', 'A'): {'52-37-0.259740.fasta': 1, '20-0-0.306216.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '18-30-0.060340.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1, '16-90-0.499308.fasta': 1}, ('Ancestral', '525', 'C', 'T'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '587', 'T', 'C'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '46-4-0.031722.fasta': 1, '50-70-0.309395.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1, '48-79-0.278710.fasta': 1}, ('Ancestral', '606', 'T', 'C'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '42-7-0.015329.fasta': 1, '58-54-0.413551.fasta': 1, '68-66-0.019926.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '651', 'G', 'A'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '46-4-0.031722.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '660', 'T', 'G'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '699', 'G', 'A'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '14-53-0.427146.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '58-54-0.413551.fasta': 1, '66-33-0.355178.fasta': 1, '60-78-0.305355.fasta': 1, '12-9-0.345404.fasta': 1}, ('Ancestral', '706', 'G', 'A'): {'52-37-0.259740.fasta': 1, '8-99-0.089017.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '68-66-0.019926.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '752', 'T', 'C'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '785', 'G', 'A'): {'52-37-0.259740.fasta': 1}, ('Ancestral', '800', 'A', 'G'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '807', 'C', 'A'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '916', 'G', 'A'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '983', 'T', 'C'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '1184', 'C', 'T'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '74-98-0.056818.fasta': 1, '70-28-0.297632.fasta': 1, '14-53-0.427146.fasta': 1, '54-16-0.210629.fasta': 1, '72-67-0.016729.fasta': 1, '18-30-0.060340.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '78-1-0.289326.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1, '76-55-0.131487.fasta': 1, '12-9-0.345404.fasta': 1, '80-3-0.454627.fasta': 1, '16-90-0.499308.fasta': 1}, ('Ancestral', '1329', 'A', 'G'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '1333', 'G', 'A'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '74-98-0.056818.fasta': 1, '70-28-0.297632.fasta': 1, '54-16-0.210629.fasta': 1, '72-67-0.016729.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '78-1-0.289326.fasta': 1, '58-54-0.413551.fasta': 1, '66-33-0.355178.fasta': 1, '68-66-0.019926.fasta': 1, '60-78-0.305355.fasta': 1, '76-55-0.131487.fasta': 1, '80-3-0.454627.fasta': 1}, ('Ancestral', '1391', 'A', 'G'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '14-53-0.427146.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1, '12-9-0.345404.fasta': 1}, ('Ancestral', '1429', 'A', 'G'): {'52-37-0.259740.fasta': 1, '20-0-0.306216.fasta': 1, '32-77-0.273127.fasta': 1, '56-61-0.198293.fasta': 1, '36-97-0.371712.fasta': 1, '74-98-0.056818.fasta': 1, '70-28-0.297632.fasta': 1, '54-16-0.210629.fasta': 1, '72-67-0.016729.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '78-1-0.289326.fasta': 1, '58-54-0.413551.fasta': 1, '66-33-0.355178.fasta': 1, '68-66-0.019926.fasta': 1, '60-78-0.305355.fasta': 1, '76-55-0.131487.fasta': 1, '80-3-0.454627.fasta': 1, '34-73-0.334718.fasta': 1}, ('Ancestral', '1449', 'C', 'T'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '1481', 'A', 'G'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '46-4-0.031722.fasta': 1, '50-70-0.309395.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1, '48-79-0.278710.fasta': 1}, ('Ancestral', '1491', 'C', 'T'): {'52-37-0.259740.fasta': 1, '8-99-0.089017.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1, '10-83-0.076895.fasta': 1}, ('Ancestral', '1523', 'G', 'A'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '74-98-0.056818.fasta': 1, '70-28-0.297632.fasta': 1, '54-16-0.210629.fasta': 1, '72-67-0.016729.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '66-33-0.355178.fasta': 1, '68-66-0.019926.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '1547', 'G', 'A'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '1602', 'C', 'A'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '1641', 'A', 'G'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '1742', 'A', 'G'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '1764', 'A', 'G'): {'52-37-0.259740.fasta': 1, '8-99-0.089017.fasta': 1, '20-0-0.306216.fasta': 1, '38-12-0.232429.fasta': 1, '26-82-0.187728.fasta': 1, '30-62-0.206087.fasta': 1, '4-25-0.459532.fasta': 1, '32-77-0.273127.fasta': 1, '56-61-0.198293.fasta': 1, '6-11-0.092686.fasta': 1, '36-97-0.371712.fasta': 1, '28-5-0.191505.fasta': 1, '22-48-0.304350.fasta': 1, '14-53-0.427146.fasta': 1, '54-16-0.210629.fasta': 1, '2-52-0.362219.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '42-7-0.015329.fasta': 1, '24-10-0.056004.fasta': 1, '58-54-0.413551.fasta': 1, '0-23-0.098532.fasta': 1, '60-78-0.305355.fasta': 1, '12-9-0.345404.fasta': 1, '10-83-0.076895.fasta': 1}, ('Ancestral', '1790', 'C', 'T'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '1817', 'G', 'A'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '14-53-0.427146.fasta': 1, '54-16-0.210629.fasta': 1, '18-30-0.060340.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1, '12-9-0.345404.fasta': 1, '16-90-0.499308.fasta': 1}, ('Ancestral', '1830', 'A', 'T'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '74-98-0.056818.fasta': 1, '70-28-0.297632.fasta': 1, '54-16-0.210629.fasta': 1, '72-67-0.016729.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '78-1-0.289326.fasta': 1, '58-54-0.413551.fasta': 1, '66-33-0.355178.fasta': 1, '68-66-0.019926.fasta': 1, '60-78-0.305355.fasta': 1, '76-55-0.131487.fasta': 1, '80-3-0.454627.fasta': 1}, ('Ancestral', '1961', 'A', 'G'): {'52-37-0.259740.fasta': 1, '38-12-0.232429.fasta': 1, '56-61-0.198293.fasta': 1, '74-98-0.056818.fasta': 1, '70-28-0.297632.fasta': 1, '54-16-0.210629.fasta': 1, '72-67-0.016729.fasta': 1, '64-65-0.413309.fasta': 1, '40-57-0.343879.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '66-33-0.355178.fasta': 1, '68-66-0.019926.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '1966', 'G', 'A'): {'52-37-0.259740.fasta': 1, '64-65-0.413309.fasta': 1, '58-54-0.413551.fasta': 1}, ('Ancestral', '1997', 'A', 'G'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '74-98-0.056818.fasta': 1, '70-28-0.297632.fasta': 1, '54-16-0.210629.fasta': 1, '72-67-0.016729.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '66-33-0.355178.fasta': 1, '68-66-0.019926.fasta': 1, '60-78-0.305355.fasta': 1, '76-55-0.131487.fasta': 1, '80-3-0.454627.fasta': 1}, ('Ancestral', '2079', 'T', 'C'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '72-67-0.016729.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '2096', 'T', 'A'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '74-98-0.056818.fasta': 1, '70-28-0.297632.fasta': 1, '54-16-0.210629.fasta': 1, '72-67-0.016729.fasta': 1, '64-65-0.413309.fasta': 1, '40-57-0.343879.fasta': 1, '62-88-0.463081.fasta': 1, '78-1-0.289326.fasta': 1, '50-70-0.309395.fasta': 1, '58-54-0.413551.fasta': 1, '44-89-0.015900.fasta': 1, '66-33-0.355178.fasta': 1, '68-66-0.019926.fasta': 1, '60-78-0.305355.fasta': 1, '76-55-0.131487.fasta': 1, '80-3-0.454627.fasta': 1, '48-79-0.278710.fasta': 1}, ('Ancestral', '2112', 'A', 'G'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '74-98-0.056818.fasta': 1, '70-28-0.297632.fasta': 1, '54-16-0.210629.fasta': 1, '72-67-0.016729.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '78-1-0.289326.fasta': 1, '58-54-0.413551.fasta': 1, '66-33-0.355178.fasta': 1, '68-66-0.019926.fasta': 1, '60-78-0.305355.fasta': 1, '80-3-0.454627.fasta': 1}, ('Ancestral', '2246', 'A', 'G'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '74-98-0.056818.fasta': 1, '70-28-0.297632.fasta': 1, '54-16-0.210629.fasta': 1, '72-67-0.016729.fasta': 1, '40-57-0.343879.fasta': 1, '62-88-0.463081.fasta': 1, '78-1-0.289326.fasta': 1, '42-7-0.015329.fasta': 1, '46-4-0.031722.fasta': 1, '50-70-0.309395.fasta': 1, '44-89-0.015900.fasta': 1, '66-33-0.355178.fasta': 1, '68-66-0.019926.fasta': 1, '60-78-0.305355.fasta': 1, '76-55-0.131487.fasta': 1, '80-3-0.454627.fasta': 1, '48-79-0.278710.fasta': 1}, ('Ancestral', '2256', 'A', 'G'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '74-98-0.056818.fasta': 1, '70-28-0.297632.fasta': 1, '54-16-0.210629.fasta': 1, '72-67-0.016729.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '78-1-0.289326.fasta': 1, '58-54-0.413551.fasta': 1, '66-33-0.355178.fasta': 1, '68-66-0.019926.fasta': 1, '60-78-0.305355.fasta': 1, '76-55-0.131487.fasta': 1, '80-3-0.454627.fasta': 1}, ('Ancestral', '2310', 'G', 'C'): {'52-37-0.259740.fasta': 1, '64-65-0.413309.fasta': 1}, ('Ancestral', '2336', 'C', 'A'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '74-98-0.056818.fasta': 1, '70-28-0.297632.fasta': 1, '54-16-0.210629.fasta': 1, '72-67-0.016729.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '78-1-0.289326.fasta': 1, '58-54-0.413551.fasta': 1, '66-33-0.355178.fasta': 1, '68-66-0.019926.fasta': 1, '60-78-0.305355.fasta': 1, '76-55-0.131487.fasta': 1, '80-3-0.454627.fasta': 1}, ('Ancestral', '2362', 'T', 'G'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '74-98-0.056818.fasta': 1, '70-28-0.297632.fasta': 1, '54-16-0.210629.fasta': 1, '72-67-0.016729.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '78-1-0.289326.fasta': 1, '46-4-0.031722.fasta': 1, '50-70-0.309395.fasta': 1, '58-54-0.413551.fasta': 1, '44-89-0.015900.fasta': 1, '66-33-0.355178.fasta': 1, '68-66-0.019926.fasta': 1, '60-78-0.305355.fasta': 1, '76-55-0.131487.fasta': 1, '80-3-0.454627.fasta': 1, '48-79-0.278710.fasta': 1}, ('Ancestral', '2388', 'A', 'T'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '2455', 'A', 'T'): {'52-37-0.259740.fasta': 1}, ('Ancestral', '2465', 'C', 'A'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1, '48-79-0.278710.fasta': 1}, ('Ancestral', '2483', 'C', 'T'): {'52-37-0.259740.fasta': 1}, ('Ancestral', '2518', 'C', 'T'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '74-98-0.056818.fasta': 1, '70-28-0.297632.fasta': 1, '54-16-0.210629.fasta': 1, '72-67-0.016729.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '78-1-0.289326.fasta': 1, '58-54-0.413551.fasta': 1, '66-33-0.355178.fasta': 1, '68-66-0.019926.fasta': 1, '60-78-0.305355.fasta': 1, '76-55-0.131487.fasta': 1, '80-3-0.454627.fasta': 1}, ('Ancestral', '2539', 'C', 'T'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '74-98-0.056818.fasta': 1, '70-28-0.297632.fasta': 1, '54-16-0.210629.fasta': 1, '72-67-0.016729.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '78-1-0.289326.fasta': 1, '58-54-0.413551.fasta': 1, '66-33-0.355178.fasta': 1, '68-66-0.019926.fasta': 1, '60-78-0.305355.fasta': 1, '76-55-0.131487.fasta': 1, '80-3-0.454627.fasta': 1}, ('Ancestral', '2628', 'G', 'A'): {'52-37-0.259740.fasta': 1, '20-0-0.306216.fasta': 1, '38-12-0.232429.fasta': 1, '32-77-0.273127.fasta': 1, '56-61-0.198293.fasta': 1, '36-97-0.371712.fasta': 1, '54-16-0.210629.fasta': 1, '18-30-0.060340.fasta': 1, '64-65-0.413309.fasta': 1, '40-57-0.343879.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1, '34-73-0.334718.fasta': 1, '16-90-0.499308.fasta': 1}, ('Ancestral', '2673', 'C', 'T'): {'52-37-0.259740.fasta': 1, '38-12-0.232429.fasta': 1, '56-61-0.198293.fasta': 1, '74-98-0.056818.fasta': 1, '70-28-0.297632.fasta': 1, '54-16-0.210629.fasta': 1, '72-67-0.016729.fasta': 1, '64-65-0.413309.fasta': 1, '40-57-0.343879.fasta': 1, '62-88-0.463081.fasta': 1, '78-1-0.289326.fasta': 1, '42-7-0.015329.fasta': 1, '46-4-0.031722.fasta': 1, '50-70-0.309395.fasta': 1, '58-54-0.413551.fasta': 1, '44-89-0.015900.fasta': 1, '68-66-0.019926.fasta': 1, '60-78-0.305355.fasta': 1, '76-55-0.131487.fasta': 1, '80-3-0.454627.fasta': 1, '48-79-0.278710.fasta': 1}, ('Ancestral', '2723', 'T', 'C'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '2734', 'A', 'T'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '74-98-0.056818.fasta': 1, '70-28-0.297632.fasta': 1, '54-16-0.210629.fasta': 1, '72-67-0.016729.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '78-1-0.289326.fasta': 1, '42-7-0.015329.fasta': 1, '46-4-0.031722.fasta': 1, '50-70-0.309395.fasta': 1, '58-54-0.413551.fasta': 1, '66-33-0.355178.fasta': 1, '68-66-0.019926.fasta': 1, '60-78-0.305355.fasta': 1, '80-3-0.454627.fasta': 1, '48-79-0.278710.fasta': 1}, ('Ancestral', '2779', 'C', 'T'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '74-98-0.056818.fasta': 1, '22-48-0.304350.fasta': 1, '54-16-0.210629.fasta': 1, '72-67-0.016729.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '66-33-0.355178.fasta': 1, '68-66-0.019926.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '2832', 'G', 'A'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1}, ('Ancestral', '2851', 'A', 'G'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '54-16-0.210629.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '2877', 'G', 'A'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '74-98-0.056818.fasta': 1, '54-16-0.210629.fasta': 1, '72-67-0.016729.fasta': 1, '64-65-0.413309.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1}, ('Ancestral', '2879', 'A', 'G'): {'52-37-0.259740.fasta': 1, '56-61-0.198293.fasta': 1, '14-53-0.427146.fasta': 1, '54-16-0.210629.fasta': 1, '62-88-0.463081.fasta': 1, '58-54-0.413551.fasta': 1, '60-78-0.305355.fasta': 1, '12-9-0.345404.fasta': 1}, ('Ancestral', '2943', 'A', 'C'): {'52-37-0.259740.fasta': 1}, ('Ancestral', '3024', 'C', 'T'): {'52-37-0.259740.fasta': 1, '8-99-0.089017.fasta': 1, '4-25-0.459532.fasta': 1, '56-61-0.198293.fasta': 1, '6-11-0.092686.fasta': 1, '14-53-0.427146.fasta': 1, '54-16-0.210629.fasta': 1, '2-52-0.362219.fasta': 

,#CHROM,POS,REF,ALT,52-37-0.259740.fasta,56-61-0.198293.fasta,54-16-0.210629.fasta,62-88-0.463081.fasta,58-54-0.413551.fasta,60-78-0.305355.fasta,...,30-62-0.206087.fasta,4-25-0.459532.fasta,6-11-0.092686.fasta,28-5-0.191505.fasta,22-48-0.304350.fasta,2-52-0.362219.fasta,24-10-0.056004.fasta,0-23-0.098532.fasta,40-57-0.343879.fasta,44-89-0.015900.fasta
0,Ancestral,61,A,G,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,Ancestral,117,G,T,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,Ancestral,141,G,A,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Ancestral,152,A,G,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
4,Ancestral,173,G,A,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2084,Ancestral,8046,C,T,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2085,Ancestral,8523,A,G,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2086,Ancestral,8621,T,C,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2087,Ancestral,8996,A,G,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2088,Ancestral,9076,T,C,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [18]:
parsnp_data.duplicated(["#CHROM", "POS", "REF", "ALT"]).sum()

np.int64(0)

In [19]:
def get_shared(parsnp_data, ska_data, bronko):
    df1 = parsnp_data
    df2 = ska_data
    df3 = bronko

    variant_cols = ["#CHROM", "POS", "REF", "ALT"]

    def add_suffix(df, suffix):
        sample_cols = [c for c in df.columns if c not in variant_cols]
        return df.rename(columns={c: f"{c}_{suffix}" for c in sample_cols})

    df1_ = add_suffix(df1, "1")
    df2_ = add_suffix(df2, "2")
    df3_ = add_suffix(df3, "3")

    merged = (
        df1_
        .merge(df2_, on=variant_cols, how="outer")
        .merge(df3_, on=variant_cols, how="outer")
    )
    

    fasta_cols = [c for c in merged.columns if ".fasta" in c]

    merged[fasta_cols] = (
        merged[fasta_cols]
        .fillna(0)
        .astype(int)
    )

    sample_cols = [c for c in df1.columns[9:] if c not in variant_cols]


    
    results = []
    ska_missed = []

    for c in sample_cols:
        col1 = f"{c}_1"
        col2 = f"{c}_2"
        col3 = f"{c}_3"

        a = merged[col1] == 1
        b = merged[col2] == 1
        d = merged[col3] == 1

        only_1 = (a & ~b & ~d).sum()
        only_2 = (~a & b & ~d).sum()
        only_3 = (~a & ~b & d).sum()

        shared_12_only = (a & b & ~d).sum()
        shared_13_only = (a & ~b & d).sum()
        shared_23_only = (~a & b & d).sum()

        shared_123 = (a & b & d).sum()
        
        if shared_13_only:
            print(c)
            ska_missed.append(c)

        results.append({
            "sample": c,
            "only_1": int(only_1),
            "only_2": int(only_2),
            "only_3": int(only_3),
            "shared_12_only": int(shared_12_only),
            "shared_13_only": int(shared_13_only),
            "shared_23_only": int(shared_23_only),
            "shared_123": int(shared_123)
        })

    overlap_df = pd.DataFrame(results)
    overlap_df
    return overlap_df, merged, ska_missed

In [20]:
overlap_df, merged, ska_missed = get_shared(parsnp_data, ska_data, bronko)
overlap_df

24-10-0.056004.fasta
14-53-0.427146.fasta
26-82-0.187728.fasta
74-98-0.056818.fasta
54-16-0.210629.fasta
52-37-0.259740.fasta
62-88-0.463081.fasta
28-5-0.191505.fasta
16-90-0.499308.fasta
66-33-0.355178.fasta
46-4-0.031722.fasta
6-11-0.092686.fasta
50-70-0.309395.fasta
40-57-0.343879.fasta
30-62-0.206087.fasta
70-28-0.297632.fasta
72-67-0.016729.fasta
56-61-0.198293.fasta
32-77-0.273127.fasta
48-79-0.278710.fasta
44-89-0.015900.fasta
64-65-0.413309.fasta
76-55-0.131487.fasta
60-78-0.305355.fasta
42-7-0.015329.fasta
38-12-0.232429.fasta
8-99-0.089017.fasta
68-66-0.019926.fasta
12-9-0.345404.fasta
0-23-0.098532.fasta
78-1-0.289326.fasta
58-54-0.413551.fasta
18-30-0.060340.fasta
2-52-0.362219.fasta
22-48-0.304350.fasta
34-73-0.334718.fasta
36-97-0.371712.fasta
4-25-0.459532.fasta
10-83-0.076895.fasta
20-0-0.306216.fasta
80-3-0.454627.fasta

,sample,only_1,only_2,only_3,shared_12_only,shared_13_only,shared_23_only,shared_123
0,24-10-0.056004.fasta,53,0,0,0,163,0,78
1,14-53-0.427146.fasta,67,0,0,0,188,0,92
2,26-82-0.187728.fasta,62,0,0,0,200,0,76
3,74-98-0.056818.fasta,5,0,0,0,49,0,98
4,54-16-0.210629.fasta,22,0,0,0,104,0,94
5,52-37-0.259740.fasta,27,0,0,0,89,0,104
6,62-88-0.463081.fasta,22,0,0,0,89,0,98
7,28-5-0.191505.fasta,30,0,0,0,164,0,69
8,16-90-0.499308.fasta,40,0,1,0,157,0,96
9,66-33-0.355178.fasta,10,0,1,0,62,0,90
10,46-4-0.031722.fasta,33,0,1,0,151,0,93
11,6-11-0.092686.fasta,17,0,0,0,126,0,89
12,50-70-0.309395.fasta,23,0,0,1,138,0,94
13,40-57-0.343879.fasta,31,0,0,0,163,0,83
14,30-62-0.206087.fasta,33,0,0,0,168,0,83
15,70-28-0.297632.fasta,3,0,0,1,48,0,84
16,72-67-0.016729.fasta,2,0,0,0,50,0,98
17,56-61-0.198293.fasta,23,0,0,0,97,0,96
18,32-77-0.273127.fasta,49,0,0,0,221,0,99
19,48-79-0.278710.fasta,19,0,0,0,136,0,97
20,44-89-0.015900.fasta,22,0,0,0,135,0,87
21,64-65-0.413309.fasta,24,0,0,0,94,0,99
22,76-55-0.131487.fasta,13,0,0,0,92,0,70
23,60-78-0.305355.fasta,21,0,0,0,127,0,97
24,42-7-0.015329.fasta,28,0,0,0,157,0,79
25,38-12-0.232429.fasta,27,0,0,0,173,0,83
26,8-99-0.089017.fasta,26,0,1,0,131,0,90
27,68-66-0.019926.fasta,14,0,1,0,73,0,93
28,12-9-0.345404.fasta,64,0,0,0,203,0,88
29,0-23-0.098532.fasta,13,0,0,0,115,0,82
30,78-1-0.289326.fasta,6,0,0,0,67,0,64
31,58-54-0.413551.fasta,31,0,0,0,107,0,97
32,18-30-0.060340.fasta,39,0,1,0,150,0,101
33,2-52-0.362219.fasta,14,0,0,0,118,0,81
34,22-48-0.304350.fasta,53,0,1,0,172,0,70
35,34-73-0.334718.fasta,56,0,1,0,233,0,95
36,36-97-0.371712.fasta,60,0,0,0,231,1,95
37,4-25-0.459532.fasta,17,0,0,0,125,0,90
38,10-83-0.076895.fasta,27,0,1,0,129,0,91
39,20-0-0.306216.fasta,40,0,1,0,162,0,102
40,80-3-0.454627.fasta,7,0,0,0,61,0,58

In [21]:
overlap_df.iloc[:, 1:].sum()

only_1            1173
only_2               0
only_3              10
shared_12_only       2
shared_13_only    5418
shared_23_only       1
shared_123        3623
dtype: int64

In [22]:
def count_cluster_misses(merged, cluster_dict):

    miss_counts = {}

    for fname, clusters in cluster_dict.items():

        col1 = f"{fname}_1"  # parsnp
        col3 = f"{fname}_3"  # bronko

        if col1 not in merged.columns or col3 not in merged.columns:
            miss_counts[fname] = 0
            continue

        # flatten clusters → unique positions
        cluster_positions = set()
        for tup in clusters:
            cluster_positions.update(tup)

        if not cluster_positions:
            miss_counts[fname] = 0
            continue

        # filter merged to those positions
        subset = merged[merged["POS"].isin(cluster_positions)]

        # parsnp present but bronko absent
        misses = ((subset[col1] == 1) & (subset[col3] == 0)).sum()

        miss_counts[fname] = int(misses)

    return pd.Series(miss_counts)

out = count_cluster_misses(merged, close_locations_4)
out.sum()

np.int64(877)

In [23]:

out = count_cluster_misses(merged, close_locations)
out.sum()

np.int64(1048)

In [24]:
pos_set = set(pos for tup in close_locations_4["74-98-0.056818.fasta"] for pos in tup)
pos_set

{np.int64(4018),
 np.int64(4020),
 np.int64(5006),
 np.int64(5010),
 np.int64(7255),
 np.int64(7256),
 np.int64(7976),
 np.int64(7981),
 np.int64(8540),
 np.int64(8541)}

In [25]:
merged[(merged['74-98-0.056818.fasta_1'] == 1)  & (merged['POS'].isin(pos_set))][['POS', '74-98-0.056818.fasta_1', '74-98-0.056818.fasta_3']]

       POS  74-98-0.056818.fasta_1  74-98-0.056818.fasta_3
999   4018                       1                       0
1001  4020                       1                       0
1218  5006                       1                       0
1220  5010                       1                       1
1751  7255                       1                       1
1752  7256                       1                       1
1910  7976                       1                       1
1911  7981                       1                       1
2051  8540                       1                       1
2052  8541                       1                       1

In [26]:
out = count_cluster_misses(merged, cluster_locations)
out.sum()

np.int64(826)