In [1]:
import pandas as pd

In [2]:
cov_metadata = pd.read_csv('cov_complete_metadata_ncbi.csv')
cov_metadata

/tmp/ipykernel_3728449/2262378669.py:1: DtypeWarning: Columns (2,7) have mixed types. Specify dtype option on import or set low_memory=False.
  cov_metadata = pd.read_csv('cov_complete_metadata_ncbi.csv')

,Accession,GenBank_RefSeq,Assembly,Organism_Name,Species,Pangolin,PangoVersions,Genotype,Isolate,Length,Nuc_Completeness,Geo_Location,Country,Host,Tissue_Specimen_Source,Submitters,Collection_Date,Release_Date,Molecule_type
0,NC_045512,RefSeq,GCF_009858895.1,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus pandemicum,B,4.3.1/1.34/v0.1.12/0.3.19/0.6.3,NaN,Wuhan-Hu-1,29903,complete,China,China,Homo sapiens,NaN,"Wu,F., Zhao,S., Yu,B., Chen,Y.M., Wang,W., Son...",2019-12,2020-01-13,ssRNA(+)
1,PX489781,GenBank,NaN,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus pandemicum,PP.1,4.3.1/1.34/v0.1.12/0.3.19/0.6.3,NaN,PA-CDC-9375635,29777,complete,USA: Pennsylvania,USA,Homo sapiens,NaN,"Kelleher,A., Sabin,S., Lu,X., Lourenco,P.R., M...",2025-06-02,2025-11-04,ssRNA(+)
2,PX489782,GenBank,NaN,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus pandemicum,XFG,4.3.1/1.34/v0.1.12/0.3.19/0.6.3,NaN,PA-CDC-9375723,29728,complete,USA: Pennsylvania,USA,Homo sapiens,NaN,"Kelleher,A., Sabin,S., Lu,X., Lourenco,P.R., M...",2025-07-21,2025-11-04,ssRNA(+)
3,PX489783,GenBank,NaN,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus pandemicum,XFG,4.3.1/1.34/v0.1.12/0.3.19/0.6.3,NaN,PA-CDC-9375722,29780,complete,USA: Pennsylvania,USA,Homo sapiens,NaN,"Kelleher,A., Sabin,S., Lu,X., Lourenco,P.R., M...",2025-07-21,2025-11-04,ssRNA(+)
4,PX489785,GenBank,NaN,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus pandemicum,XFG.3,4.3.1/1.34/v0.1.12/0.3.19/0.6.3,NaN,PA-CDC-9375726,29781,complete,USA: Pennsylvania,USA,Homo sapiens,NaN,"Kelleher,A., Sabin,S., Lu,X., Lourenco,P.R., M...",2025-06-30,2025-11-04,ssRNA(+)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1097420,MN988713,GenBank,set:MN988713,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus pandemicum,B,4.3.1/1.34/v0.1.12/0.3.19/0.6.3,NaN,IL-CDC-02983522-001,29882,complete,USA: Illinois,USA,Homo sapiens,"lung, oronasopharynx","Tao,Y., Queen,K., Paden,C.R., Zhang,J., Li,Y.,...",2020-01-21,2020-01-25,ssRNA(+)
1097421,MN938384,GenBank,set:MN938384,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus pandemicum,A,4.3.1/1.34/v0.1.12/0.3.19/0.6.3,NaN,2019-nCoV_HKU-SZ-002a_2020,29838,complete,China: Shenzhen,China,Homo sapiens,oronasopharynx,"Chan,J.F.-W., Yuan,S., Kok,K.H., To,K.K.-W., C...",2020-01-10,2020-01-24,ssRNA(+)
1097422,MN975262,GenBank,set:MN975262,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus pandemicum,A,4.3.1/1.34/v0.1.12/0.3.19/0.6.3,NaN,2019-nCoV_HKU-SZ-005b_2020,29891,complete,China,China,Homo sapiens,"lung, oronasopharynx","Chan,J.F.-W., Yuan,S., Kok,K.H., To,K.K.-W., C...",2020-01-11,2020-01-24,ssRNA(+)
1097423,MN985325,GenBank,set:MN985325,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus pandemicum,A,4.3.1/1.34/v0.1.12/0.3.19/0.6.3,NaN,WA-CDC-02982586-001,29882,complete,USA,USA,Homo sapiens,oronasopharynx,"Harcourt,J., Tamin,A., Lu,X., Kamili,S., Sakth...",2020-01-19,2020-01-24,ssRNA(+)
1097424,MN908947,GenBank,set:MN908947,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus pandemicum,B,4.3.1/1.34/v0.1.12/0.3.19/0.6.3,NaN,Wuhan-Hu-1,29903,complete,China,China,Homo sapiens,NaN,"Wu,F., Zhao,S., Yu,B., Chen,Y.M., Wang,W., Son...",2019-12,2020-01-12,ssRNA(+)

In [3]:
counts = cov_metadata['Pangolin'].value_counts()

In [4]:
counts[counts > 500]

Pangolin
BA.1.1       104150
BA.2.12.1     80632
B.1.1.7       67733
BA.2          52542
BA.5.2.1      37583
              ...
P.1.4           516
BA.4.1.1        511
B.1.1.63        510
XFG.3           509
LP.8.1          506
Name: count, Length: 194, dtype: int64

## the nextstrain metadata file will need to be downloaded (was 11.9GB for me)

In [ ]:
nextstrain = pd.read_csv('metadata.tsv', delimiter='\t')
nextstrain

In [ ]:
nextstrain.columns

Index(['strain', 'virus', 'gisaid_epi_isl', 'genbank_accession',
       'genbank_accession_rev', 'sra_accession', 'date', 'region', 'country',
       'division', 'location', 'region_exposure', 'country_exposure',
       'division_exposure', 'segment', 'length', 'host', 'age', 'sex',
       'Nextstrain_clade', 'pango_lineage', 'GISAID_clade', 'originating_lab',
       'submitting_lab', 'authors', 'url', 'title', 'paper_url',
       'date_submitted', 'date_updated', 'sampling_strategy', 'database',
       'clade_nextstrain', 'clade_who', 'Nextclade_pango', 'immune_escape',
       'ace2_binding', 'missing_data', 'divergence', 'nonACGTN', 'coverage',
       'rare_mutations', 'reversion_mutations', 'potential_contaminants',
       'QC_missing_data', 'QC_mixed_sites', 'QC_rare_mutations',
       'QC_snp_clusters', 'QC_frame_shifts', 'QC_stop_codons',
       'QC_overall_score', 'QC_overall_status', 'frame_shifts', 'deletions',
       'insertions', 'substitutions', 'aaSubstitutions', 'clock_deviation'],
      dtype='object')

In [ ]:
len(nextstrain['strain'].value_counts())

9394690

In [ ]:
filtered_nextstrain = nextstrain[(nextstrain['genbank_accession'] != '?') & (nextstrain['date'] != '?')]

In [ ]:
filtered_nextstrain

,strain,virus,gisaid_epi_isl,genbank_accession,genbank_accession_rev,sra_accession,date,region,country,division,...,QC_frame_shifts,QC_stop_codons,QC_overall_score,QC_overall_status,frame_shifts,deletions,insertions,substitutions,aaSubstitutions,clock_deviation
1,ARG/210316-1/2021,ncov,?,OL989073,OL989073.1,NaN,2021-03-15,South America,Argentina,Argentina,...,good,good,14.062500,good,NaN,NaN,NaN,"C66T,C241T,C3037T,A4926G,A5574G,C7564A,C8139T,...","N:R203K,N:G204R,ORF1a:D1554G,ORF1a:Y1770C,ORF1...",2.0
2,ARG/210524-2/2021,ncov,?,OL989092,OL989092.1,NaN,2021-05-17,South America,Argentina,Argentina,...,good,good,4.340278,good,NaN,NaN,NaN,"A22G,C241T,C913T,C3037T,C3177T,C3267T,C5388A,C...","N:D3L,N:R203K,N:G204R,N:S235F,N:A308S,ORF1a:P9...",3.0
3,ARG/210610-225/2021,ncov,?,OL989093,OL989093.1,NaN,2021-06-07,South America,Argentina,Argentina,...,good,good,50.173611,mediocre,NaN,NaN,NaN,"C241T,C913T,A1967G,C3037T,C3177T,C3267T,C5388A...","N:D3L,N:P151L,N:R203K,N:G204R,N:S235F,ORF1a:T5...",0.0
4,ARG/210613-39/2021,ncov,?,OL989084,OL989084.1,NaN,2021-06-07,South America,Argentina,Argentina,...,good,good,6.250000,good,NaN,NaN,NaN,"C241T,T733C,A2596G,C2749T,C3037T,C3828T,A5648C...","M:H125Y,N:P80R,N:R203K,N:G204R,ORF1a:S1188L,OR...",0.0
5,ARG/210615-23/2021,ncov,?,OL989096,OL989096.1,NaN,2021-06-14,South America,Argentina,Argentina,...,good,good,39.062500,mediocre,NaN,NaN,NaN,"T175C,C241T,C3037T,C4002T,C7124T,T7424G,C8655T...","N:P13L,N:A119P,N:R203K,N:G204R,N:G214C,N:D377Y...",-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8902866,musmusculus/USA/Beta-WTP10/2023,ncov,?,PV241312,PV241312.1,NaN,2023,North America,USA,USA,...,good,good,0.000000,good,NaN,"11288-11296,22283-22291",NaN,"G174T,C241T,C1059T,A2692T,C3037T,G5230T,A10323...","E:T30I,E:P71L,N:R32H,N:T205I,ORF1a:T265I,ORF1a...",?
8902867,musmusculus/USA/Beta-WTP15/2024,ncov,?,PV241314,PV241314.1,NaN,2024,North America,USA,USA,...,good,good,0.000000,good,NaN,"11288-11296,22283-22291",NaN,"G174T,C241T,C1059T,A2692T,C3037T,G5230T,A10323...","E:T30I,E:P71L,N:T205I,ORF1a:T265I,ORF1a:K1655N...",?
8902868,musmusculus/USA/Beta-WTP20/2024,ncov,?,PV241316,PV241316.1,NaN,2024,North America,USA,USA,...,good,good,0.000000,good,NaN,"11288-11296,22283-22291",NaN,"G174T,C241T,C1059T,A2692T,C3037T,G5230T,A10323...","E:T30I,E:P71L,N:T205I,ORF1a:T265I,ORF1a:K1655N...",?
8902869,musmusculus/USA/Beta-WTP5/2023,ncov,?,PV241310,PV241310.1,NaN,2023,North America,USA,USA,...,good,good,0.000000,good,NaN,"11288-11296,22283-22291",NaN,"G174T,C241T,C1059T,A2692T,C3037T,G5230T,A10323...","E:P71L,N:T205I,ORF1a:T265I,ORF1a:K1655N,ORF1a:...",?
8902870,tiger/NY/040420/2020,ncov,?,MT365033,MT365033.1,NaN,2020-04-02,North America,USA,New York,...,good,good,0.000000,good,NaN,NaN,NaN,"C241T,C1059T,C3037T,C14408T,A23403G,G25563T","ORF1a:T265I,ORF1b:P314L,ORF3a:Q57H,S:D614G",0.0

In [ ]:
filtered_nextstrain['Nextstrain_clade'].value_counts()

Nextstrain_clade
21J (Delta)        2740281
21K (Omicron)      1591343
21L (Omicron)      1103074
22B (Omicron)       743461
20I (Alpha, V1)     645619
22E (Omicron)       196764
22C (Omicron)       177440
23A (Omicron)       167572
21I (Delta)         151090
20A                 130121
20B                 115295
20E (EU1)           108107
24A (Omicron)       105689
22A (Omicron)        98040
20G                  88674
20C                  77478
23F (Omicron)        58781
21A (Delta)          54220
21C (Epsilon)        46009
23D (Omicron)        43582
23B (Omicron)        42654
21F (Iota)           38139
24E (Omicron)        37460
20J (Gamma, V3)      32116
22D (Omicron)        30775
recombinant          28291
23C (Omicron)        27966
22F (Omicron)        23795
24C (Omicron)        19482
24F (Omicron)        17696
24B (Omicron)        16735
23E (Omicron)        15840
19A                  14551
25C (Omicron)        13997
25A (Omicron)        13808
20F                  11463
20H (Beta, V2)       10315
24G (Omicron)         9792
19B                   7818
23I (Omicron)         7604
20D                   6248
21H (Mu)              6232
23H (Omicron)         6030
23G (Omicron)         4303
25B (Omicron)         3809
21D (Eta)             3182
24H (Omicron)         3020
21G (Lambda)          2248
21M (Omicron)         1952
21B (Kappa)           1052
24D (Omicron)          559
24I (Omicron)          322
 (Omicron)             200
21E (Theta)             50
Name: count, dtype: int64

In [ ]:
merged_data = cov_metadata.merge(filtered_nextstrain, left_on="Accession", right_on="genbank_accession", how="left")

In [ ]:
merged_data

,Accession,GenBank_RefSeq,Assembly,Organism_Name,Species,Pangolin,PangoVersions,Genotype,Isolate,Length,...,QC_frame_shifts,QC_stop_codons,QC_overall_score,QC_overall_status,frame_shifts,deletions,insertions,substitutions,aaSubstitutions,clock_deviation
0,NC_045512,RefSeq,GCF_009858895.1,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus pandemicum,B,4.3.1/1.34/v0.1.12/0.3.19/0.6.3,NaN,Wuhan-Hu-1,29903,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,PX489781,GenBank,NaN,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus pandemicum,PP.1,4.3.1/1.34/v0.1.12/0.3.19/0.6.3,NaN,PA-CDC-9375635,29777,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PX489782,GenBank,NaN,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus pandemicum,XFG,4.3.1/1.34/v0.1.12/0.3.19/0.6.3,NaN,PA-CDC-9375723,29728,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,PX489783,GenBank,NaN,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus pandemicum,XFG,4.3.1/1.34/v0.1.12/0.3.19/0.6.3,NaN,PA-CDC-9375722,29780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,PX489785,GenBank,NaN,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus pandemicum,XFG.3,4.3.1/1.34/v0.1.12/0.3.19/0.6.3,NaN,PA-CDC-9375726,29781,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1097420,MN988713,GenBank,set:MN988713,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus pandemicum,B,4.3.1/1.34/v0.1.12/0.3.19/0.6.3,NaN,IL-CDC-02983522-001,29882,...,good,good,64.0,mediocre,NaN,NaN,NaN,NaN,NaN,6.0
1097421,MN938384,GenBank,set:MN938384,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus pandemicum,A,4.3.1/1.34/v0.1.12/0.3.19/0.6.3,NaN,2019-nCoV_HKU-SZ-002a_2020,29838,...,good,good,0.0,good,NaN,NaN,NaN,"C8782T,T28144C,C29095T",ORF8:L84S,0.0
1097422,MN975262,GenBank,set:MN975262,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus pandemicum,A,4.3.1/1.34/v0.1.12/0.3.19/0.6.3,NaN,2019-nCoV_HKU-SZ-005b_2020,29891,...,good,good,0.0,good,NaN,NaN,NaN,"C8782T,C9561T,T15607C,T28144C,C29095T","ORF1a:S3099L,ORF8:L84S",2.0
1097423,MN985325,GenBank,set:MN985325,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus pandemicum,A,4.3.1/1.34/v0.1.12/0.3.19/0.6.3,NaN,WA-CDC-02982586-001,29882,...,good,good,0.0,good,NaN,NaN,NaN,"C8782T,C18060T,T28144C",ORF8:L84S,0.0
1097424,MN908947,GenBank,set:MN908947,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus pandemicum,B,4.3.1/1.34/v0.1.12/0.3.19/0.6.3,NaN,Wuhan-Hu-1,29903,...,good,good,0.0,good,NaN,NaN,NaN,NaN,NaN,7.0

In [ ]:
merged_data['Nextstrain_clade'].value_counts()

Nextstrain_clade
22B (Omicron)      192152
21K (Omicron)      173881
21J (Delta)        145821
21L (Omicron)       88240
22C (Omicron)       81160
20I (Alpha, V1)     67537
22E (Omicron)       59564
22A (Omicron)       34257
20G                 32875
24A (Omicron)       25924
20C                 25869
20A                 25108
20B                 21323
21F (Iota)          14588
21C (Epsilon)       10575
20J (Gamma, V3)      9390
21I (Delta)          8963
24E (Omicron)        8207
20F                  8084
21A (Delta)          6117
22D (Omicron)        5776
24B (Omicron)        3614
23E (Omicron)        3524
24C (Omicron)        3362
24F (Omicron)        3220
19B                  3034
25A (Omicron)        2688
24G (Omicron)        2611
20E (EU1)            2370
recombinant          2344
19A                  2289
23C (Omicron)        1589
25C (Omicron)        1346
22F (Omicron)        1135
20D                   740
21G (Lambda)          585
23I (Omicron)         530
20H (Beta, V2)        481
21D (Eta)             465
24H (Omicron)         440
25B (Omicron)         406
23F (Omicron)         133
21B (Kappa)           123
23B (Omicron)         121
23D (Omicron)          97
24D (Omicron)          91
23A (Omicron)          85
24I (Omicron)          59
21H (Mu)               49
23H (Omicron)          22
21M (Omicron)          21
23G (Omicron)           9
21E (Theta)             8
Name: count, dtype: int64

In [ ]:
first_last = pd.concat([
    merged_data.loc[merged_data.groupby('Nextstrain_clade')['Release_Date'].idxmin()],
    merged_data.loc[merged_data.groupby('Nextstrain_clade')['Release_Date'].idxmax()]
]).sort_values(['Nextstrain_clade', 'Release_Date'])